#runtime: python37
#env: flex
#runtime_config:
#  python_version: 3.7
#1)Below is used for flask app with out using wsgi server
#entrypoint: python main.py
#2)Below is used for WSGI with flask
#entrypoint: gunicorn -b :$PORT main:app
#1)Below is used for uWSGI with flask
#entrypoint: uwsgi --http :$PORT --wsgi-file main.py --callable app
#application: first-gcp-proj-286407

runtime: python
env: flex
api_version: 1
threadsafe: true

runtime_config:
  python_version: 3.7

handlers:
  - url: /.*
    script: auto
  - url: /static
    static_dir: static
  - url: /css
    static_dir: static/css
  - url: /js
    static_dir: static/js
  - url: /img
    static_dir: static/img
  - url: /(.*\.(gif|png|jpg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg)$

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 2
    #min_pending_latency: 30ms
    #max_pending_latency: automatic
    #max_concurrent_requests: 2
resources:
      cpu: 2
      memory_gb: 8
      disk_size_gb: 25
service: v12


entrypoint: gunicorn -b :$PORT main:app