
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: psweb-app-gke-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psweb
  template:
    metadata:
      labels:
        app: psweb
    spec:
      containers:
      - name: psweb-app-deploy
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: us-central1-docker.pkg.dev/hcl-gcp-project/hcl-proj-repo/psweb-app:latest
        #image: gcr.io/hcl-gcp-project/psweb-app:v1
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
